version: '3.8'
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rick
      POSTGRES_DB: rickandmortydb
    container_name: rickandmorty
    volumes:
      - ./postgres_data:/var/lib/postgresql/data